spring.application.name=incubators-shop-backend

server.port=${PORT:8080}

# ===================================================
# DATABASE CONFIGURATION (Aiven Cloud MySQL)
# ===================================================
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===================================================
# EMAIL CONFIGURATION (Gmail SMTP Engine)
# ===================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=sasivenkatgowdnda@gmail.com
#spring.mail.password=pqbcanvnojzsofdj
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===================================================
# CUSTOM APP PROPERTIES
# ===================================================
#incubators.shop.admin-email=sasivenkatgowdnda@gmail.com
#incubators.shop.frontend-url=http://localhost:5173
incubators.shop.admin-email=${MAIL_USER}
incubators.shop.frontend-url=${FRONTEND_URL:http://localhost:5173}

# Dynamic Multipart File Limits (Uncomment if managing image uploads)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB